/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <GLCD.h>
#include <Move_Right.h>
#include <Move_Right_aliases.h>
#include <Move_Left.h>
#include <Move_Left_aliases.h>
#include <Move_Up.h>
#include <Move_Up_aliases.h>
#include <Move_Down.h>
#include <Move_Down_aliases.h>
#include <Blast.h>
#include <Blast_aliases.h>
#include <Blast_Red.h>
#include <Blast_Red_aliases.h>
#include <Blast_Blue.h>
#include <Blast_Blue_aliases.h>
#include <Blast_Green.h>
#include <Blast_Green_aliases.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <SS.h>
#include <SS_aliases.h>
#include <SCLK.h>
#include <SCLK_aliases.h>
#include <Com_Block.h>
#include <Com_Block_PVT.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <GLCD_Reset.h>
#include <GLCD_Reset_aliases.h>
#include <GLCD_SPIM_SCB.h>
#include <GLCD_SPIM_SCB_SPI_UART.h>
#include <GLCD_SPIM_SCB_PINS.h>
#include <GLCD_SPIM_SCB_SPI_UART_PVT.h>
#include <GLCD_SPIM_SCB_PVT.h>
#include <Com_Block_IntClock.h>
#include <GLCD_SPIM_SCB_ss0_m.h>
#include <GLCD_SPIM_SCB_ss0_m_aliases.h>
#include <GLCD_SPIM_SCB_mosi_m.h>
#include <GLCD_SPIM_SCB_mosi_m_aliases.h>
#include <GLCD_SPIM_SCB_miso_m.h>
#include <GLCD_SPIM_SCB_miso_m_aliases.h>
#include <GLCD_SPIM_SCB_sclk_m.h>
#include <GLCD_SPIM_SCB_sclk_m_aliases.h>
#include <GLCD_SPIM_SCB_ss1_m.h>
#include <GLCD_SPIM_SCB_ss1_m_aliases.h>
#include <GLCD_SPIM_SCB_ss2_m.h>
#include <GLCD_SPIM_SCB_ss2_m_aliases.h>
#include <GLCD_SPIM_SCB_ss3_m.h>
#include <GLCD_SPIM_SCB_ss3_m_aliases.h>
#include <GLCD_SPIM_SCB_SCBCLK.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

